### PR TITLE
Fallback to archive.org URLs for failed downloads of FOSS packages

### LINKED ISSUE #1682: Upload FOSS mods to the Internet Archive, allow clients to fallback
# Proposal

Similar to #935, we can upload FOSS mods to the Internet Archive. There is example code over at KSP-CKAN/NetKAN-bot for uploading to the IA, the sticking point is the resulting uploaded file.

An [Item](https://archive.org/about/faqs.php#1084) per Mod Version made sense to me, but open to ideas. As the metadata per version could change.

The big rub is the filename. We have options, that have consequences.
1. Use similar method to cache, Generate hash from URL and derive the filename
   - :+1: We already do it in a similar manner, simple to implement
   - :+1: Easy
   - :+1: Requires no altering of the metadata
   - :-1: Client needs to derive the url
   -  :-1: Download URL changes, mod gets re-mirrored
   - :-1: Major mod hosting site goes offline, _a lot_ of mods get re-mirrored.
   - :-1: If a file changes it won't get re-uploaded
2. Generate a hash from the identifier/version, derive the filename
   - :+1: Easy
   - :+1: Requires no altering of the metadata
   - :+1: Download url changes, file is not re-uploaded.
   - :-1: Client needs to derive the url
   - :-1: If a file changes it won't get re-uploaded
3. Generate a hash on the downloaded file and add it to the metadata
   - :+1: We have a hash of the file
   - :+1: Client doesn't have to derive the filename
   - :-1: Requires altering the metadata
   - :-1: Requires spec change
   - :+1: :-1: If a file changes we could re-upload it and add it to the metadata. This may not always be desirable.

I came up with 2 whilst I was writing this.. It's the option I'm currently leaning towards. Pinging @dbent @pjf being more across internals of the Client code base and @Dazpoet @plague006 @politas being across the metadata.
# Implementation

Option 3 was decided on.

**Phase 1**
- [x] Get NetKAN to produce the field
- [x] Start uploading things. 95% of the code is already done, just add a webhook shim and watch CKAN-meta for changes.
- [x] Scan for any hooks we missed daily with git diff $(git rev-list -n1 --before="yesterday" master) --name-only KSP-CKAN/NetKAN-bot#49

**Phase 2**
- [x] Implement whatever we decide with CKAN-meta/NetKAN amalgamation - #3890
- [ ] Rearchitect the indexer (I have some solid ideas).
- [ ] Crawling head/api checks all day
- [ ] Full inflation daily on NetKAN_repo/NetKAN/
- [ ] Continue to inflate on demand (Captures both NetKAN + CKAN-meta)
- [ ] ~~Scan NetKAN_repo for any changes we missed git diff $(git rev-list -n1 --before="yesterday" master) --name-only -p NetKAN_repo/CKAN-meta/~~ covered by full inflation as all former ckans are treated the same way as netkans.

**Phase 3** (Though technically this can be done anytime)
- [ ] CKAN Schema update
- [ ] CKAN Client implementation

**Phase 4**
- [x] Slowly crawl the entire NetKAN_repo/CKAN-meta
  - 6088 mods mirrored
  - 6476 mods with download hashes
  - 356 mods which don't allow mirriong
  - 16 mods with hashes but dead urls 
  - 137 mods which failed to inflate (could be dead url or changed zip)

### PR DESCRIPTION
**Pull request by HebaruSan**
## Background

SpaceDock broke today, which is fun. VITAS reports that it looks like a denial of service attack.

The NetKAN bot has been uploading all permissively-licensed mods to https://archive.org/details/kspckanmods for quite a while now. Many or most of the SpaceDock downloads that are now failing, could in principle fall back to archive.org URLs. Such a feature could also help us deal with GitHub's download throttling or SpaceDock's certificate expirations.

## Changes

Now if the primary download fails for a permissively licensed mod, we try to find it on archive.org as a fallback.

Internally this involves defining a `fallbackUrl` property in `DownloadTarget` and `NetAsyncDownloaderDownloadPart`, both populated from a new `CkanModule.InternetArchiveDownload` property, which itself checks a new `License.Redistributable` property based on a new copy of the list from NetKAN-bot. Then if a download fails, we check whether it has a fallback URL, and if so and if we haven't already tried it, we try it. If the fallback fails as well, then we continue with the normal steps for a failed download.

Fixes #1682.

### CODE REVIEW

**Comment by HebaruSan** [comment]
(The failing test is itself due to SpaceDock being down.)

File: Core/Types/CkanModule.cs [hunk 1]
```diff
@@ -623,6 +623,22 @@ public string DescribeInstallStanzas()
             return string.Join(", ", descriptions);
         }
 
+        /// <summary>
+        /// Return an archive.org URL for this download, or null if it's not there.
+        /// The filenames look a lot like the filenames in Net.Cache, but don't be fooled!
+        /// Here it's the first 8 characters of the SHA1 of the DOWNLOADED FILE, not the URL!
+        /// </summary>
```
Comment (techman83) [inline Core/Types/CkanModule.cs]: Yeah, the hash of that file will remain consistent. The url may not.
```
Produces a filename based of the first 8 digits in sha1 hash,
the 'identifier' and the 'version' in the metadata if the
download_hash exists. Returns '0' if there is no download hash
or has an content type other than zip/gz/tar/tar.gz.
```
There are some [tests](https://github.com/KSP-CKAN/NetKAN-bot/blob/master/t/App/KSP_CKAN/Metadata/Ckan.t#L71) that ensure the correct filenames are generated.

File: Core/Types/CkanModule.cs [hunk 2]
```diff
@@ -623,6 +623,22 @@ public string DescribeInstallStanzas()
...
+            get
+            {
+                return license.All(l => l.Redistributable)
+                    ? new Uri(
+                        $"https://archive.org/download/{identifier}-{version}/{download_hash.sha1.Substring(0, 8)}-{identifier}-{version}.zip")
+                    : null;
+            }
+        }
+
         /// <summary>
```
Comment (techman83) [inline Core/Types/CkanModule.cs]: Some tests of the filename generation could be useful, but I wouldn't treat this as a blocker.

File: Core/Types/CkanModule.cs (hunk 1 above)
Comment (HebaruSan) [reply Core/Types/CkanModule.cs]: Yup, either way makes enough sense to me. I just wanted to note it explicitly since we have two different 8-digit hexadecimal filename prefixes floating around, and it's not easy to tell that they're (supposed to be) different at a glance.

Comment (techman83) [reply Core/Types/CkanModule.cs]: Yeah, actually makes sense for URL in the cache. If the url changes, you probably do want to re-download.
