### PR TITLE
`ckan ksp fake/clone` fixes

### LINKED ISSUE #2637: `ckan ksp fake` crashes with no arguments
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake`

See #2627 for background on this command.

**What did you expect to happen?**

Print help about how to use the subcommand

**What happened instead?**

NRE

**CKAN error codes (if applicable):** 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
Segmentation fault
```

### LINKED ISSUE #2638: `ckan ksp clone` crashes with no arguments
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp clone`

See #2627 for background on this command.

**What did you expect to happen?**

Print help about how to use the subcommand

**What happened instead?**

`ArgumentNullException`

**CKAN error codes (if applicable):** 
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.SortedList`2.IndexOfKey(TKey key)
   at System.Collections.Generic.SortedList`2.ContainsKey(TKey key)
   at CKAN.KSPManager.HasInstance(String name)
   at CKAN.CmdLine.KSP.CloneInstall(CloneOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

### LINKED ISSUE #2639: `ckan ksp fake` doesn't create all the subdirs it should
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake FAKETEST1 fake1 1.2.2 none`

See #2627 for background on this command.

**What did you expect to happen?**

Based on [this exchange in #2627](https://github.com/KSP-CKAN/CKAN/pull/2627#discussion_r244621435), I expected [the folders created by the validation scripts](https://github.com/KSP-CKAN/xKAN-meta_testing/blob/36ccd470cde1c6a02a8a3fc267e2eddad2b6640c/NetKAN/build.sh#L54-L59) to be present. This would allow us to replace the dummy KSP creation functions in the validation scripts with much simpler calls to the new `ckan ksp fake` command.

**What happened instead?**

It created this (Windows `tree /f` command):

```
fake1
│   buildID.txt
│   buildID64.txt
│   readme.txt
│
├───CKAN
│   │   installed-FAKETEST1.ckan
│   │   registry.json
│   │
│   └───history
│           installed-FAKETEST1-2019-01-08_06-11-51.ckan
│
└───GameData
```

Several directories are missing (the ones linked in the exchanged mentioned above):

- `Ships`
- `Ships/VAB`
- `Ships/SPH`
- `Ships/@thumbs`
- `Ships/@thumbs/VAB`
- `Ships/@thumbs/SPH`

### LINKED ISSUE #2640: `ckan ksp fake` throws exception on two-piece version
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake FAKETEST3 fake3 1.2 none`

See #2627 for background on this command.

**What did you expect to happen?**

Either create a 1.2.0 install, or a 1.2.2 install, or tell me I need to be more specific

**What happened instead?**

`ArgumentOutOfRangeException` printed (twice). We shouldn't be printing an exception with stack trace here, because it's not some unexpected weird glitch, it's a known case of failed validation of user input. This should just print a simple message explaining why we failed to create the fake instance.

Aside from that, the message itself is fairly baffling. If I was a novice user, I'm not sure I could figure out what I did wrong. The answer is that all parts of the MAJOR.MINOR.PATCH version info need to be filled in, but this only conveys that indirectly.

**CKAN error codes (if applicable):** 

```
237 [1] ERROR CKAN.CmdLine.KSP (null) - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at CKAN.Versioning.KspVersion.FindKnownVersion()
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at CKAN.Versioning.KspVersion.FindKnownVersion()
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
Examples for valid version formats: 1.5.0 | 1.5.1 | 1.6.0.2395
```

### LINKED ISSUE #2641: `ckan ksp fake` prints exception for future versions
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake FAKETEST4 fake4 1.6.1 none`

See #2627 for background on this command.

**What did you expect to happen?**

Either create a fake install with 1.6.1 in the readme.txt, or tell me that version 1.6.1 doesn't exist.

**What happened instead?**

`System.ArgumentOutOfRangeException` printed (twice).

As in #2640, we don't need a stack trace here, just a short message explaining why "1.6.1" isn't allowed.

And the final line is misleading, because the problem here isn't anything to do with the format.

**CKAN error codes (if applicable):** 

```
240 [1] ERROR CKAN.CmdLine.KSP (null) - System.ArgumentOutOfRangeException: Your specified version is invalid.
Parameter name: version
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
System.ArgumentOutOfRangeException: Your specified version is invalid.
Parameter name: version
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
Examples for valid version formats: 1.5.0 | 1.5.1 | 1.6.0.2395
```

### PR DESCRIPTION
**Pull request by DasSkelett**
@HebaruSan discovered some issues with my new two functions. This is how they behave now: 

Both functions:
Write human-readable messages if there are too few arguments provided, no error messages due to crashes.

`ckan ksp fake`:
* Creates now all subdirs requested (see https://github.com/KSP-CKAN/CKAN/pull/2627#discussion_r244621435).
* Added `--set-default` flag to make the new instance the default afterwards.
* Also, if a user inputs a version number at least with major and minor, a selection dialog is raised to select a specific version (including build) known in the build map (else a message is raised to inform him to input a version with major and Minor at least).

This logic is now added as a new method of `Versioning.KspVersion` -> `KspVersion RaiseVersionSelectionDialog(IUser)`.
Note that, despite the IUser being passed, only the cmdline User and the consoleUI User implement a `RaiseSelectionDialog`, so it won't work in the GUI without implementing a `RaiseSelectionDialog`.
Thanks @HebaruSan for the idea. 

Fixes #2641
Fixes #2640
Fixes #2639
Fixes #2638
Fixes #2637

### CODE REVIEW

**Comment by DasSkelett** [comment]
Now the new `FindKnownVersion()` is not used anymore.
I'm thinking of deleting it and maybe moving the version selection 'algorithm' from `FakeNewKSPInstall()`there, what do you suggest?

File: Cmdline/Action/KSP.cs [hunk 1]
```diff
@@ -496,47 +502,107 @@ private int SetDefaultInstall(DefaultOptions options)
...
-                if (version == null)
+                else if (possibleVersions.Count == 1)
                 {
-                    throw new ArgumentOutOfRangeException(nameof(version), "Your specified version is invalid.");
+                    version = possibleVersions.ElementAt(0);
+                }
+                else
+                {
+                    int choosen = User.RaiseSelectionDialog("The specified version is not unique, please select one:", possibleVersions.ToArray());
+                    if (choosen > 0 && choosen < possibleVersions.Count)
```
Comment (HebaruSan) [inline Cmdline/Action/KSP.cs]: Selecting 1 doesn't work; I think `RaiseSelectionDialog` returns input-1, so this should be `>= 0`:

```
ckan ksp fake fake12 fake12 1.5
1) 1.5.0.2332
2) 1.5.1.2335
Enter a number between 1 and 2 (To cancel press "c" or "n".):
1
Selection cancelled! Please call 'ckan ksp fake' again.
```

File: Cmdline/Action/KSP.cs [hunk 2]
```diff
@@ -496,47 +502,107 @@ private int SetDefaultInstall(DefaultOptions options)
...
                 }
-                if (version == null)
+                else if (possibleVersions.Count == 1)
                 {
-                    throw new ArgumentOutOfRangeException(nameof(version), "Your specified version is invalid.");
+                    version = possibleVersions.ElementAt(0);
+                }
+                else
+                {
+                    int choosen = User.RaiseSelectionDialog("The specified version is not unique, please select one:", possibleVersions.ToArray());
```
Comment (HebaruSan) [inline Cmdline/Action/KSP.cs]: Bizarrely, `RaiseSelectionDialog` validates its message parameter and then never prints it! So the list of versions appears without an explanation. Do you feel like fixing `RaiseSelectionDialog` in this PR? It's here:

https://github.com/KSP-CKAN/CKAN/blob/421332c3abf30e3cf52adc81d6cd77743c2592d2/Cmdline/ConsoleUser.cs#L73-L228

**Comment by HebaruSan** [comment]
Yes, I think moving the version selection logic makes sense so it could be shared among UIs. In the past this has been done by passing an `IUser` parameter.

**Comment by HebaruSan** [comment]
It would be really nice to have a `--set-default` parameter to `ckan ksp fake`, to make the new fake instance the default instance. This would be handy for the validation scripts.

File: Cmdline/Action/KSP.cs (hunk 1 above)
Comment (DasSkelett) [reply Cmdline/Action/KSP.cs]: Oh yes, did fix that for the rest of the  new code, but oversaw this one.

File: Cmdline/Action/KSP.cs (hunk 2 above)
Comment (DasSkelett) [reply Cmdline/Action/KSP.cs]: Sure.

**Comment by DasSkelett** [comment]
Ooookay, I need some help understanding our Users/IUsers:
What are the virtual `Display...()` methods for?
Wouldn't it be easier to just override the `Raise..()` methods in each User class and thus derive them from `IUser` instead of `NullUser`?

**Comment by DasSkelett** [comment]
Okay, will do that, but on a new branch and PR, to keep it spearated.

**Comment by politas** [comment]
Almost messed me up with that PR title. Bash ran the command when I tried to commit!
