### PR TITLE
Adapt Curse API to new widget

### LINKED ISSUE #2178: Curse API is broken
**CKAN Version:** HEAD

**Operating System:** Ubuntu 17.04

**The issue you are experiencing:** 

http://status.ksp-ckan.org/

All mods hosted on Curse now say:

> Could not get the mod from Curse, reason: project/ABCXYZ cannot be found on curse.com.

A test is also failing:

```
$ ./build test

1) Error : Tests.NetKAN.Sources.Curse.CurseApiTests.GetsModCorrectly
CKAN.Kraken : Could not get the mod from Curse, reason: Due to breaking changes at the curse.com website, this widget is currently available. Please visit the project page directly at: https://mods.curse.com/project/220221 Please email sryan@curse.com with any questions..
  at CKAN.NetKAN.Sources.Curse.CurseApi.GetMod (System.Int32 modId) [0x00034] in <896b7ef4c8e0431fb2e00da75ce0c276>:0 
  at Tests.NetKAN.Sources.Curse.CurseApiTests.GetsModCorrectly () [0x00012] in <fc05fcb18e70447b9a563b5729c30b33>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 
```

Extracting the error for readability:

> Due to breaking changes at the curse.com website, this widget is currently available. Please visit the project page directly at: https://mods.curse.com/project/220221 Please email sryan@curse.com with any questions..

The client **can** still download and install mods hosted on Curse. It's just the checking for new updates that's broken.

Interesting timing just days after GitHub broke travis...

### PR DESCRIPTION
**Pull request by HebaruSan**
Closes #2178.

This pull request updates the Curse API code to work with the latest changes to the widget.

- The base URL is changed
- No longer need json suffix in URL
- `files` is now an array rather than a dictionary
- `authors` is now moved into `members` array with `username` as property name
- The version is now embedded in `name`

After these changes, the tests all pass and `netkan.exe` generates files that match previous versions except for specifics of URLs.

### CODE REVIEW

**Comment by Olympic1** [comment]
I will look at this tonight

File: Netkan/Sources/Curse/CurseApi.cs [hunk 1]
```diff
@@ -8,10 +8,10 @@ namespace CKAN.NetKAN.Sources.Curse
 {
     internal sealed class CurseApi : ICurseApi
     {
-        private static readonly ILog Log = LogManager.GetLogger(typeof (CurseApi));
+        private static readonly ILog Log = LogManager.GetLogger(typeof(CurseApi));
 
-        public static string CurseApiBase = "https://widget.mcf.li/project/";
-        public static string CurseApiEnd = ".json";
+        private static string CurseApiBase = "https://api.cfwidget.com/project/";
+        private static string CurseApiEnd = "";
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseApi.cs]: If we don't use this anymore, we might as well remove it.

File: Netkan/Sources/Curse/CurseApi.cs [hunk 2]
```diff
@@ -26,18 +26,15 @@ public CurseMod GetMod(int modId)
...
             // Check if the mod has been removed from Curse and if it corresponds to a KSP mod.
             var error = JsonConvert.DeserializeObject<CurseError>(json);
-
-            if (error.code != 0)
-            {
-                var errorMessage = string.Format("Could not get the mod from Curse, reason: {0}.", error.message);
-                throw new Kraken(errorMessage);
-            }
-            else if (!error.game.Equals("Kerbal Space Program"))
+            if (!string.IsNullOrEmpty(error.error))
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseApi.cs]: Can we use `IsNullOrWhiteSpace` for an extra check for spaces?

File: Netkan/Sources/Curse/CurseMod.cs [hunk 3]
```diff
@@ -34,7 +36,7 @@ public CurseFile Latest()
         /// <returns>The home</returns>
         public string GetProjectUrl()
         {
-            return "http://kerbal.curseforge.com/projects/" + ModId;
+            return "https://www.curseforge.com/project/" + id;
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseMod.cs]: This gives a 404, the old link works fine

File: Netkan/Sources/Curse/CurseMod.cs [hunk 4]
```diff
@@ -69,19 +71,21 @@ public string GetName()
...
 
-        public static CurseMod FromJson(int modId, string json)
+        public static CurseMod FromJson(string json)
         {
             CurseMod mod = JsonConvert.DeserializeObject<CurseMod>(json);
-            mod.ModId = modId;
-            foreach (CurseFile file in mod.files.Values)
-            {
-                file.Mod = mod;
-            }
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseMod.cs]: Why do you delete all this? This works fine if you delete `.Values`

File: Netkan/Sources/Curse/CurseMod.cs [hunk 5]
```diff
@@ -10,22 +10,24 @@ internal class CurseMod
     {
         [JsonProperty] public string license;
         [JsonProperty] public string title;
-        //[JsonProperty] public string short_description;
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseMod.cs]: We can pull the `description` from curse if you uncomment line 81 in `NetKAN/Transformers/CurseTransformer.cs`.

Comment (Olympic1) [reply Netkan/Sources/Curse/CurseMod.cs]: Also in `CurseTransformer.cs` change `curseMod.authors` to `curseMod.members` on line 88.

File: Netkan/Sources/Curse/CurseFile.cs [hunk 6]
```diff
@@ -30,22 +22,24 @@ public class CurseFile
...
-        public String GetDownloadUrl()
+        /// <returns>
+        /// The download URL
+        /// </returns>
+        public string GetDownloadUrl()
         {
-            if (_downloadUrl == null)
+            if (string.IsNullOrEmpty(_downloadUrl))
             {
-                _downloadUrl = CurseApi.ResolveRedirect(new Uri(Mod.GetPageUrl() + "/files/" + id + "/download")).ToString();
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseFile.cs]: This also still works on my test.

File: Netkan/Sources/Curse/CurseMod.cs (hunk 4 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseMod.cs]: It creates circular references (mod -> file, file -> mod) that never get explicitly cleaned up and therefore probably causes garbage leakage. And it's not used for anything.

File: Netkan/Sources/Curse/CurseApi.cs (hunk 1 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseApi.cs]: OK, will do.

File: Netkan/Sources/Curse/CurseApi.cs (hunk 2 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseApi.cs]: Sure.

File: Netkan/Sources/Curse/CurseMod.cs (hunk 5 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseMod.cs]: Cool, good idea. I assume we need to remove the `short_` part to match the API. Will do.

`curseMod.members` is a list of objects with more data than just the list of strings needed by `author`, so we can't use them interchangeably. That's why `curseMod.authors` is now replaced with a property that analyzes `members`.

File: Netkan/Sources/Curse/CurseMod.cs (hunk 3 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseMod.cs]: OK, will revert.

File: Netkan/Sources/Curse/CurseFile.cs (hunk 6 above)
Comment (HebaruSan) [reply Netkan/Sources/Curse/CurseFile.cs]: I'll change it back. I think I was trying to rewrite it to rely only on properties available in the new API's JSON, but if the old stuff still works then we might as well still use it.

File: Netkan/Sources/Curse/CurseMod.cs (hunk 5 above)
Comment (techman83) [reply Netkan/Sources/Curse/CurseMod.cs]: From a "I've not looked at this code or the new API" perspective, I'm generally in favour of moving to new APIs sooner rather than later unless there is a compelling reason not to.

File: Tests/NetKAN/Sources/Curse/CurseApiTests.cs [hunk 7]
```diff
@@ -43,16 +43,12 @@ public void GetsModCorrectly()
...
             var latestVersion = result.Latest();
 
-            Assert.That(result.ModId, Is.EqualTo(220221));
-            Assert.That(result.authors, Is.Not.Null);
+            Assert.That(result.id, Is.EqualTo(220221));
+            Assert.That(result.members, Is.Not.Null);
             Assert.That(result.thumbnail, Is.Not.Null);
             Assert.That(result.license, Is.Not.Null);
             Assert.That(result.title, Is.Not.Null);
-            //Assert.That(result.short_description, Is.Not.Null);
```
Comment (Olympic1) [inline Tests/NetKAN/Sources/Curse/CurseApiTests.cs]: Uncomment this to test descriptions

File: Tests/NetKAN/Transformers/CurseTransformerTests.cs [hunk 8]
```diff
@@ -43,17 +43,14 @@ private static CurseMod MakeTestMod()
             {
                 license = "CC-BY",
                 title = "Dogecoin Flag",
-                //short_description = "Such test. Very unit. Wow.",
```
Comment (Olympic1) [inline Tests/NetKAN/Transformers/CurseTransformerTests.cs]: Uncomment this too

File: Netkan/Sources/Curse/CurseFile.cs [hunk 9]
```diff
@@ -80,13 +75,11 @@ public string GetFileVersion()
...
             if (_fileVersion == null)
             {
-                // Matches the last group of numbers letters and dots before the .zip extension, staring at a number or a 'v' and a number
-                Match match = Regex.Match(GetDownloadUrl(), "(v?[0-9][0-9a-z.]*[0-9a-z])[^0-9]*\\.zip");
-                if (match.Groups.Count > 1) _fileVersion = match.Groups[1].Value;
-
-                // The id is unique across all files, and is always incrementing.
-                // This format also assures, that any "real" version precedes them.
-                else _fileVersion = GetCurseIdVersion();
+                Match match = Regex.Match(name, "(v?[0-9][0-9a-z.]*[0-9a-z])[^0-9]*\\.zip");
```
Comment (Olympic1) [inline Netkan/Sources/Curse/CurseFile.cs]: Can `name` be changed back to `GetDownloadUrl()`, otherwise the `KIS.netkan` won't work. I tried changing the regex pattern, but couldn't get it work.

**Comment by Olympic1** [comment]
Final changes requested then this is good to go.

**Comment by HebaruSan** [comment]
Changes made. Thanks for the review!

**Comment by HebaruSan** [comment]
The status page still has a lot of "Specified id is not a KSP mod", which isn't in the source anymore.

@techman83, is the bot using an up to date netkan.exe?

**Comment by techman83** [comment]
@HebaruSan Netkan downloads the latest build artifact from AWS

Current version on S3
```
leon@beast /tmp $ (rm netkan.exe || true) && wget -q http://ckan-travis.s3-website-us-east-1.amazonaws.com/netkan.exe && mono netkan.exe --version
rm: cannot remove 'netkan.exe': No such file or directory
v1.22.7-PRE+bd1c5daa6a5a
```
Current version the bot is running.
```
netkan@ckan-bot:~/NetKAN$ mono netkan.exe --version
v1.22.7-PRE+bd1c5daa6a5a
```
Which is not the latest merged commit.
