### PR TITLE
Check all dependencies for compatibility checking

### LINKED ISSUE #1105: gui does not mark mod with missing dependency red
Once "Kerbal Construction Time RP-0 Config" is selected, the gui says that Module RP-0 has not been found. RP-0 (Realistic Progression) is a dependency of that config.
The Gui should mark this config red, like it does with conflicting mods.

### LINKED ISSUE #1646: Improved Availability Status
See KSP-CKAN/NetKAN#3511

Even though `USI-Core` is compatiable with KSP 1.1.0 it is marked _unavailable_ because one of its dependencies, `FirespitterCore` is not compatible with KSP 1.1.0. To be consistent this should mean that all mods that are compatible with KSP 1.1.0 but depend on `USI-Core` should also be marked _unavailable_ because one of their 2nd degree dependencies is unavailable. In other words, availability status should be determined by traversing the entire dependency tree, not just direct dependencies.

On a related note, we should have some mechanism by which users can see _why_ a mod is unavailable. So for instance you could do something like:

```
> ckan unavailable
Mods unavailable for KSP 1.1.0

* FirespiterCore (v7.1.5) - Firespitter Core
  Incompatible KSP version: 1.0.5
* USI-Core (0.2.0.0) - USI Core
  Unavailable dependency: FirespitterCore
* USI-NuclearRockets (0.2.0.0) - 'Project Orion' Nuclear Pulse Engine
  Unavailable dependency: USI-Core
```

To keep the list managable the `unavailable` command should only consider the _latest_ version of any unavailable mod (No one really cares why a mod released 2 years ago is unavailable with the latest KSP).

### LINKED ISSUE #2231: Compatibility checking should traverse all dependencies
Currently, when we do a check for mod availability, we only check one level, and then leave it to the installation process to fail if there are second or third order dependencies that fail. I think our availability checking process should follow this process, and it should be in the core, utilised by all UIs:

availability flowchart

The list of Checked ModVersions should be initialised before starting into this cross-recursive cycle.
I'd appreciate feedback on this. Obviously, this process simply checks availability, without adding any mods to an install list, which would need to be a separate process.

### LINKED ISSUE #2849: [Bug]  DependencyNotSatisfied installing OPM
Background
----------
* Operating System: Windows 10 Pro
* CKAN Version: 1.26.4
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
CKAN throws an error when I check the box to add OPM.  Error message below.

**Steps to reproduce**
1. Open CKAN, select 1.7.3 install
2. Don't mark any other KSP versions as compatible
3. Check the box for `OuterPlanetsMod`
4. Exception!
   image

**Expected behavior**
No error.

**CKAN error code (if applicable):**

```
************** Exception Text **************
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>d__284.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

<details><summary>Mod list</summary>

https://pastebin.com/WXaz7j7h

```json
{
	"kind": "metapackage",
	"abstract": "A list of modules installed on the KSP_1.7.3 KSP instance",
	"name": "installed-KSP_1.7.3",
	"license": "unknown",
	"version": "2019.08.21.12.25.40",
	"identifier": "installed-KSP_1.7.3",
	"spec_version": "v1.6",
	"recommends": [
		{
			"name": "ToolbarController"
		},
		{
			"name": "ProceduralFairings"
		},
		{
			"name": "NehemiahEngineeringOrbitalScience"
		},
		{
			"name": "DistantObject"
		},
		{
			"name": "NearFutureElectrical-Core"
		},
		{
			"name": "KerbalJointReinforcementContinued"
		},
		{
			"name": "EasyVesselSwitch"
		},
		{
			"name": "DockingPortSoundFX"
		},
		{
			"name": "Chatterer"
		},
		{
			"name": "NearFutureProps"
		},
		{
			"name": "CommunityCategoryKit"
		},
		{
			"name": "MechJeb2"
		},
		{
			"name": "EditorTime"
		},
		{
			"name": "ContractConfigurator"
		},
		{
			"name": "RemoteTech"
		},
		{
			"name": "KAS"
		},
		{
			"name": "ModuleManager"
		},
		{
			"name": "KRASH"
		},
		{
			"name": "CommunityTechTree"
		},
		{
			"name": "ContractConfigurator-CleverSats"
		},
		{
			"name": "ContractConfigurator-FieldResearch"
		},
		{
			"name": "TextureReplacer"
		},
		{
			"name": "ContractConfigurator-Tourism"
		},
		{
			"name": "CrowdSourcedScience"
		},
		{
			"name": "DistantObject-default"
		},
		{
			"name": "BetterBurnTime"
		},
		{
			"name": "NearFuturePropulsion"
		},
		{
			"name": "NearFutureSpacecraft"
		},
		{
			"name": "JSIAdvancedTransparentPods"
		},
		{
			"name": "KerbalPlanetaryBaseSystems"
		},
		{
			"name": "TweakScale"
		},
		{
			"name": "HideEmptyTechNodes"
		},
		{
			"name": "NearFutureLaunchVehicles"
		},
		{
			"name": "TacFuelBalancer"
		},
		{
			"name": "SCANsat"
		},
		{
			"name": "StageRecovery"
		},
		{
			"name": "CommunityResourcePack"
		},
		{
			"name": "BetterCrewAssignment"
		},
		{
			"name": "DynamicBatteryStorage"
		},
		{
			"name": "MagiCore"
		},
		{
			"name": "ExtraPlanetaryLaunchpads"
		},
		{
			"name": "DeployableEngines"
		},
		{
			"name": "ContractConfigurator-RemoteTech"
		},
		{
			"name": "NearFutureSolar"
		},
		{
			"name": "REPOSoftTech-Agencies"
		},
		{
			"name": "CommunityTerrainTexturePack"
		},
		{
			"name": "KIS"
		},
		{
			"name": "DMagicScienceAnimate"
		},
		{
			"name": "ContractConfigurator-KerbinSpaceStation"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Stockalike"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Inner"
		},
		{
			"name": "B9PartSwitch"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Outer"
		},
		{
			"name": "MechJebForAll"
		},
		{
			"name": "FMRSContinued"
		},
		{
			"name": "RecoveryController"
		},
		{
			"name": "SmokeScreen"
		},
		{
			"name": "NearFutureSolar-Core"
		},
		{
			"name": "K2CommandPodCont"
		},
		{
			"name": "SmartParts"
		},
		{
			"name": "KerbalKrashSystem"
		},
		{
			"name": "CustomAsteroids"
		},
		{
			"name": "OrbitalTug"
		},
		{
			"name": "AnimatedDecouplers"
		},
		{
			"name": "AutoAsparagus"
		},
		{
			"name": "EnvironmentalVisualEnhancements"
		},
		{
			"name": "EnvironmentalVisualEnhancements-HR"
		},
		{
			"name": "KEI"
		},
		{
			"name": "ClickThroughBlocker"
		},
		{
			"name": "BurstAtomicThrust"
		},
		{
			"name": "xScienceContinued"
		}
	]
}
```

</details>

### PR DESCRIPTION
**Pull request by HebaruSan**
## Problems

The Compatible and Incompatible filters in GUI check dependencies, but only one level. For example, OuterPlanetsMod depends on Kopernicus depends on ModularFlightIntegrator; if the first two are compatible and the third isn't, then OuterPlanetsMod appears to be installable but will fail.

We do extra work when loading the GUI filters, since `Registry.Available` and `Registry.Incompatible` both loop over all modules and check their dependencies, and the results are not re-used. Similarly, various operations that refresh the mod list are slower than they need to be because we re-check all those same relationships over again even if they haven't changed.

Sometimes "Available" includes incompatible modules:

- `Registry.available_modules`
- `Registry.AllAvailable`
- `Registry.SetAllAvailable`
- `Registry.HasAnyAvailable`
- `Registry.AddAvailable`
- `Registry.RemoveAvailable`
- `Registry.GetAvailableMetadata`

And sometimes it excludes them:

- `Registry.Available`
- `ckan available`

This is confusing.

## Changes

Now `Registry` uses a new `CompatibilitySorter` class to track module compatibility, which has public properties `Compatible` and `Incompatible` and a `CompatibleVersions` property to represent which versions they're compatible with. When we need the compatible or incompatible mods, we check whether the compatible versions are the same as last time, and if so, we return the same lists as previously (which solves the problem of `Registry.Available` and `Registry.Incompatible` duplicating work), otherwise we create a new `CompatibilitySorter` to compute the new compatibilities.

`CompatibilitySorter` uses a fully recursive dependency checking algorithm, so modules will only be counted as compatible if all of their dependencies are compatible. It also uses the lists of compatible and incompatible mods to speed up the search as it goes, rather than re-checking over and over whether dependencies are compatible (now that it's recursive, we don't want to re-check all of Kopernicus's dependencies over and over for all of its many depending mods).

Now "Available" means all modules, and anything that excludes incompatible mods is renamed to "Compatible". `AllAvailable` is renamed to `AvailableByIdentifier` since it doesn't return "all" of anything. `ckan available` retains its old name so users don't have to switch to a new command.

Fixes #1105.
Fixes #1646.
Fixes #2231.
Fixes #2849.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Oops, forgot about DLLs and DLCs. To be continued...

**Comment by DasSkelett** [comment]
Nice to finally see the nomenclature mess being untangled.
Should `LatestAvailable` and `LatestAvailableWithProvides` also be renamed to `LatestCompatible` and `LatestCompatibleWithProvides`?
On one hand they explicitly check for compatibility against a `KspVersionCriteria`, on the other hand they do not check compatibility with other mods. So it's something in the middle...

**Comment by HebaruSan** [comment]
I wasn't sure about those. In many places we pass `null` for the version to skip those compatibility checks, which makes them even more ambiguous. I could be persuaded if you strongly think they should be renamed, otherwise I would be comfortable leaving them alone.

**Comment by DasSkelett** [comment]
Okay, let's leave those alone.
I still have a few suggestions, opening a PR to your branch...

File: Core/Versioning/KspVersionCriteria.cs [hunk 1]
```diff
@@ -42,6 +42,21 @@ public KspVersionCriteria Union(KspVersionCriteria other)
             );
         }
 
+        public override bool Equals(object obj)
```
Comment (DasSkelett) [inline Core/Versioning/KspVersionCriteria.cs]: One more thing I just spotted:

> It would be less bad if this was an unusual special case, but any class that overrides Equals is going to get a compiler warning requesting an implementation of GetHashCode

>   KspVersionCriteria.cs(7, 18): [CS0659] 'KspVersionCriteria' overrides Object.Equals(object o) but does not override Object.GetHashCode()

:grin:

**Comment by DasSkelett** [comment]
You didn't rebase the PR on master after #2962 was merged, right?
It seems there was a NetCore update recently, this is the diff taken from the `dotnet --info` part of the Travis logs:
```diff
--- working-ci.log	2020-01-16 01:26:25.028271912 +0100
+++ failing-ci.log	2020-01-16 01:25:36.520236466 +0100
@@ -2,9 +2,9 @@
 
 .NET Core SDK (reflecting any global.json):
 
- Version:   2.1.802
+ Version:   2.1.803
 
- Commit:    177d0b2525
+ Commit:    ac31cfb390
 
 Runtime Environment:
 
@@ -16,22 +16,22 @@
 
  RID:         ubuntu.16.04-x64
 
- Base Path:   /usr/share/dotnet/sdk/2.1.802/
+ Base Path:   /usr/share/dotnet/sdk/2.1.803/
 
 Host (useful for support):
 
-  Version: 2.1.14
+  Version: 2.1.15
 
-  Commit:  57273284ef
+  Commit:  d43032d4d9
 
 .NET Core SDKs installed:
 
-  2.1.802 [/usr/share/dotnet/sdk]
+  2.1.803 [/usr/share/dotnet/sdk]
 
 .NET Core runtimes installed:
 
-  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
+  Microsoft.AspNetCore.All 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
 
-  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
+  Microsoft.AspNetCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
 
-  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
+  Microsoft.NETCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

File: Core/Versioning/KspVersionCriteria.cs (hunk 1 above)
Comment (HebaruSan) [reply Core/Versioning/KspVersionCriteria.cs]: Added.

**Comment by HebaruSan** [comment]
Right, this hasn't been rebased; both PRs were tripped up by something else, apparently some third party changes in net-core. Do we have enough information to submit an issue to https://github.com/dotnet/core/issues ?
